Fix issues running tests on Linux - one difference is naming of symbols: on OSX an underscore is required
Fix mmap compilation error - MAP_ANONYMOUS is not posix?

    $ chez --script auto.scm
    Performing integers tests ...
    test 0:0 ...startup.c: In function 'allocate_protected_space':
    startup.c:55:19: error: 'MAP_ANONYMOUS' undeclared (first use in this function)
                       MAP_ANONYMOUS | MAP_PRIVATE,
                       ^~~~~~~~~~~~~
    startup.c:55:19: note: each undeclared identifier is reported only once for each function it appears in
    make: *** [stst] Error 1
    Exception in make: could not build target